# Data Extraction from the downloaded the dataset
Defining the base directory.

In [10]:
BASE_PATH = "dataset"

Read the CSV's present in the dataset using *Pandas*.

In [11]:
import pandas as pd
import os

train_data = pd.read_csv(os.path.join(BASE_PATH, "train.csv"))
train_data

       Unnamed: 0                                        file_name  label
0               0  train_data/a6dcb93f596a43249135678dfcfc17ea.jpg      1
1               1  train_data/041be3153810433ab146bc97d5af505c.jpg      0
2               2  train_data/615df26ce9494e5db2f70e57ce7a3a4f.jpg      1
3               3  train_data/8542fe161d9147be8e835e50c0de39cd.jpg      0
4               4  train_data/5d81fa12bc3b4cea8c94a6700a477cf2.jpg      1
...           ...                                              ...    ...
79945       79945  train_data/9283b107f6274279b6f15bbe77c523aa.jpg      0
79946       79946  train_data/4c6b17fe6dd743428a45773135a10508.jpg      1
79947       79947  train_data/1ccbf96d04e342fd9f629ad55466b29e.jpg      0
79948       79948  train_data/ff960b55f296445abb3c5f304b52e104.jpg      1
79949       79949  train_data/3abd1876472f4ec988aa78f76664fbd6.jpg      0

[79950 rows x 3 columns]

In [12]:
test_data = pd.read_csv(os.path.join(BASE_PATH, "test.csv"))
test_data

                                                     id
0     test_data_v2/1a2d9fd3e21b4266aea1f66b30aed157.jpg
1     test_data_v2/ab5df8f441fe4fbf9dc9c6baae699dc7.jpg
2     test_data_v2/eb364dd2dfe34feda0e52466b7ce7956.jpg
3     test_data_v2/f76c2580e9644d85a741a42c6f6b39c0.jpg
4     test_data_v2/a16495c578b7494683805484ca27cf9f.jpg
...                                                 ...
5535  test_data_v2/483412064ff74d9d9472d606b65976d9.jpg
5536  test_data_v2/c0b49ba4081a4197b422dac7c15aea7f.jpg
5537  test_data_v2/01454aaedec140c0a3ca1f48028c41cf.jpg
5538  test_data_v2/e9adfea8b67e4791968c4c2bdd8ec343.jpg
5539  test_data_v2/ba8f4198e8d74d3394fa56c56af23442.jpg

[5540 rows x 1 columns]

Dropping the unneccessary column from the `train_data`.

In [13]:
train_data.drop("Unnamed: 0", axis=1, inplace=True)
train_data

                                             file_name  label
0      train_data/a6dcb93f596a43249135678dfcfc17ea.jpg      1
1      train_data/041be3153810433ab146bc97d5af505c.jpg      0
2      train_data/615df26ce9494e5db2f70e57ce7a3a4f.jpg      1
3      train_data/8542fe161d9147be8e835e50c0de39cd.jpg      0
4      train_data/5d81fa12bc3b4cea8c94a6700a477cf2.jpg      1
...                                                ...    ...
79945  train_data/9283b107f6274279b6f15bbe77c523aa.jpg      0
79946  train_data/4c6b17fe6dd743428a45773135a10508.jpg      1
79947  train_data/1ccbf96d04e342fd9f629ad55466b29e.jpg      0
79948  train_data/ff960b55f296445abb3c5f304b52e104.jpg      1
79949  train_data/3abd1876472f4ec988aa78f76664fbd6.jpg      0

[79950 rows x 2 columns]

Separating the *AI-Generated Images* and the *Real Images* into the separate folders.<br>
We will be using the **shutil** module.

In [21]:
import shutil

for i in range(len(train_data)):
    source = os.path.join(BASE_PATH, train_data.iloc[i,]["file_name"])
    if train_data.iloc[i,]["label"] == 1:
        destination = os.path.join(BASE_PATH, "train", "ai")
    else:
        destination = os.path.join(BASE_PATH, "train", "real")
    shutil.copy2(source, destination)

We have separated the *AI-Generated* and *Real* Images based on the *CSV File* provided in the dataset.<br>
Now, the further things will be done in another Notebook.